[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
coinflip = "HWpAveiQGMm8o9NeD1NncQ9dBMd1CtxuKbVe9cGKQZFh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd program && npx ts-mocha -p tsconfig.json -t 1000000 tests/**/*.ts"
